apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: "Address Index Api"
  name: "address-index-api"
  description: "Address Index is an application which resolves addresses"
  annotations:
    github.com/project-slug: backstage-dummy-org/address-index-api
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: "address-index-admin"
  definition: 
    $file: "./api-definitions/api-openapi.json"
